# Generated by Django 5.0.1 on 2024-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_clients_tasks_users_workers_delete_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='patronymic',
            field=models.CharField(max_length=256, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='register_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
    ]
