# Generated by Django 5.0.1 on 2024-03-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_clients_name_alter_clients_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='begin_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(verbose_name='Дэдлайн'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.workers', verbose_name='ID сотрудника'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='patronymic',
            field=models.CharField(max_length=256, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
        ),
    ]
