# Generated by Django 5.0.1 on 2024-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_tasks_begin_date_alter_tasks_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='users',
            name='patronymic',
            field=models.CharField(default='отчество', max_length=256, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='фамилия', max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(default='имя', max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='patronymic',
            field=models.CharField(default='отчество', max_length=256, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(default='фамилия', max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='имя', max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='patronymic',
            field=models.CharField(default='отчество', max_length=256, verbose_name='Отчество'),
        ),
    ]
