# Generated by Django 5.0.1 on 2024-03-06 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_users_login_remove_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.workers', verbose_name='ID сотрудника'),
        ),
    ]
